# Site settings
title: The Lendable Blog
header-img: img/landing.JPG
email: joe@lendable.io
description: "The Lendablog"
url: "http://lendable.io"
twitter_username: lendableinc
# github_username:  lendablexxx
# facebook_username:  swashbuckle
# paginate: 20
# paginate_path: "/blog/page/:num"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
