# Site settings
title: The Swashbuckle Blog
header-img: img/landing.JPG
email: joe@swashbuckle.io
description: "The Lendablog"
baseurl: "/blog"
url: "http://yourdomain.com"
twitter_username: swashbuckleinc
github_username:  joebrew
facebook_username:  swashbuckle

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
