# Site settings
title: The Swashbuckle Blog
header-img: img/landing.JPG
email: joe@swashbuckle.io
description: "The Lendablog"
url: "http://yourdomain.com"
twitter_username: swashbuckleinc
github_username:  swashbuckleblog
facebook_username:  swashbuckle
# paginate: 20
# paginate_path: "/blog/page/:num"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
