# Site settings
title: The Lendable Blog
header-img: img/phone_shop_data.png
email: joe@lendable.io
description: "Lendable blog"
url: "http://lendablemarketplace.com"
# baseurl: /blog
twitter_username: lendableinc
# github_username:  lendablexxx
# facebook_username:  swashbuckle
# paginate: 20
# paginate_path: "/blog/page/:num"
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
